// <auto-generated />
using System;
using LifeChart.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeChart.Infrastructure.Migrations
{
    [DbContext(typeof(LifeChartDbContext))]
    partial class LifeChartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("LifeChart.Domain.Entries.DailyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Functionality")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHypomanic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MedicationTaken")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MenstrualCycle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mood")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SleepHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symptoms")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyEntries");
                });

            modelBuilder.Entity("LifeChart.Domain.Medications.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("LifeChart.Domain.Medications.Medication", b =>
                {
                    b.OwnsMany("LifeChart.Domain.Medications.IntakeTime", "IntakeTimes", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("DoseCount")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MedicationId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Time")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("MedicationId");

                            b1.ToTable("IntakeTime");

                            b1.WithOwner()
                                .HasForeignKey("MedicationId");
                        });

                    b.Navigation("IntakeTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
